version: '3.5'

services:
  elastic-stack:
    build:
      context: ./elastic_stack
      dockerfile: Dockerfile    
    image: elastic-stack
    container_name: elastic-stack
    ports:
      - 5601:5601
      - 9200:9200
    environment:
        - discovery.type=single-node
    volumes:
      - elasticsearch-data:/home/elasticsearch/elasticsearch-7.17.9/data
      - kibana-data:/home/elasticsearch/kibana-7.17.9-linux-x86_64/data
      - ./data:/home/elasticsearch/parquet_files
    networks:
      - weather_network

  central_station:
    build:
      context: ./central-station
      dockerfile: Dockerfile
    image: central_station
    container_name: central_station
    volumes:
      - ./data:/data
      - ./central-station/bitcaskDB:/app/bitcaskDB
    depends_on:
      - kafka
    networks:
      - weather_network


  weather_station:
    build:
      context: ./weather-station
      dockerfile: Dockerfile
    image: weather_station
    container_name: weather_station
    depends_on:
      - kafka
    networks:
      - weather_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - weather_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    expose:
      - 9092:9092
    networks:
      - weather_network

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  weather_network:
    driver: bridge
