version: '3.5'

services:
  elastic-stack:
    build: .
    image: elastic-stack
    container_name: elastic-stack
    ports:
      - 5601:5601
      - 9200:9200
    environment:
        - discovery.type=single-node
    volumes:
      - elasticsearch-data:/home/elasticsearch/elasticsearch-7.17.9/data
      - kibana-data:/home/elasticsearch/kibana-7.17.9-linux-x86_64/data
      - ../data:/home/elasticsearch/parquet_files

volumes:
  elasticsearch-data:
  kibana-data:
